#!/usr/bin/env python
# encoding: utf-8
import sys, os
import ConfigParser
from optparse import OptionParser
# from nsb_nfv_tools.nfv_tools import UpgradeVyos
from nfv_tools import UpgradeVyos


def main():
    opt = OptionParser()
    opt.add_option('--upgrade-vyos',
                   action="store_true",
                   dest="upgrade_vyos",
                   default=False,
                   help='upgrade vyos node')
    '''
    opt.add_option('--config',
                   dest='config',
                   type=str,
                   default='/home/nsb/upgrade.config',
                   help='config file')
    '''
    opt.add_option('--upgrade-backup-vyos',
                   action="store_true",
                   dest="upgrade_backup",
                   default=False,
                   help='upgrade backup vyos node')
    opt.add_option('--upgrade-active-vyos',
                   action="store_true",
                   dest="upgrade_active",
                   default=False,
                   help='upgrade active vyos node')
    opt.add_option('--copy-image',
                   action="store_true",
                   dest="copy_image",
                   default=False,
                   help='copy vyos image to host')
    opt.add_option('--stop-nfv-monitor',
                   action="store_true",
                   dest="stop_nfv_monitor",
                   default=False,
                   help='copy vyos image to host')
    opt.add_option('--rollback-vyos',
                   action="store_true",
                   dest="rollback_vyos",
                   default=False,
                   help='rollback vyos  to 3.2')
    opt.add_option('--rollback-active',
                   action="store_true",
                   dest="rollback_active",
                   default=False,
                   help='rollback active vyos  to 3.2')
    opt.add_option('--rollback-backup',
                   action="store_true",
                   dest="rollback_backup",
                   default=False,
                   help='rollback backup vyos  to 3.2')
    opt.add_option('--gen-boot-config',
                   action="store_true",
                   dest="gen_boot_config",
                   default=False,
                   help='generate   vyos boot config')
    opt.add_option('--gen-neutron-config',
                   action="store_true",
                   dest="gen_neutron_config",
                   default=False,
                   help='generate   neutron nfv.conf')
    opt.add_option('--back-neutron-db',
                   action="store_true",
                   dest="back_neutron_db",
                   default=False,
                   help='back   neutron db')
    opt.add_option('--rollback-db',
                   action="store_true",
                   dest="rollback_db",
                   default=False,
                   help='rollback   neutron db')
    opt.add_option('--migrate-neutron-db',
                   action="store_true",
                   dest="migrate_neutron_db",
                   default=False,
                   help='migrate neutron db insert table nfv_vrouters')
    opt.add_option('--upgrade-vsd',
                   action="store_true",
                   dest="upgrade_vsd",
                   default=False,
                   help='upgrade vsd: firewalls,hostinterface,vlan,secrity rule')  
    opt.add_option('--ping-active-vyos',
                   action="store_true",
                   dest="ping_active_vyos",
                   default=False,
                   help='ping active vyos') 
    opt.add_option('--ping-backup-vyos',
                   action="store_true",
                   dest="ping_backup_vyos",
                   default=False,
                   help='ping backup vyos')
    opt.add_option('--exec-cmd-backup',
                   dest="exec_cmd_backup",
                   type=str,
                   default='',
                   help='exec cmd on  backup vyos')   
    opt.add_option('--exec-cmd-active',
                   dest="exec_cmd_active",
                   type=str,
                   default='',
                   help='exec cmd on  active vyos')     
    opt.add_option('--get-vsd-firewall',
                   action="store_true",
                   dest="get_vsd_firewall",
                   default=False,
                   help='get vsd firewall')
    opt.add_option('--gen-nfv-group',
                   action="store_true",
                   dest="gen_nfv_group",
                   default=False,
                   help='gen nfv group')
    opt.add_option('--exec-cmd-host',
                   dest="exec_cmd_host",
                   type=str,
                   default='',
                   help='exec cmd on host')

    (options, args) = opt.parse_args()
    

    copy_image   = options.copy_image
    stop_nfv_monitor = options.stop_nfv_monitor
    upgrade_vyos   = options.upgrade_vyos
    upgrade_active   = options.upgrade_active
    upgrade_backup   = options.upgrade_backup
    rollback_vyos = options.rollback_vyos
    rollback_active =  options.rollback_active
    rollback_backup = options.rollback_backup
    gen_boot_config = options.gen_boot_config
    gen_neutron_config = options.gen_neutron_config
    back_neutron_db = options.back_neutron_db
    migrate_neutron_db = options.migrate_neutron_db
    upgrade_vsd = options.upgrade_vsd
    rollback_db = options.rollback_db
    ping_backup_vyos = options.ping_backup_vyos
    ping_active_vyos = options.ping_active_vyos
    exec_cmd_active = options.exec_cmd_active
    exec_cmd_backup = options.exec_cmd_backup
    get_vsd_firewall =  options.get_vsd_firewall
    gen_nfv_group = options.gen_nfv_group
    exec_cmd_host = options.exec_cmd_host

    #conf        = options.config
    #config = ConfigParser.ConfigParser()
    #config.read(conf)
    

    if copy_image:
        UpgradeVyos().copy_img()
    if stop_nfv_monitor:
        UpgradeVyos().stop_nfv_monitor_service()
    if upgrade_vyos:
        UpgradeVyos().upgrade_vyos()
    if upgrade_active:
        UpgradeVyos().upgrade_active_vyos()
    if upgrade_backup:
        UpgradeVyos().upgrade_backup_vyos()
    if rollback_vyos:
        UpgradeVyos().rollback_vyos()
    if rollback_active:
        UpgradeVyos().rollback_active_vyos()
    if rollback_backup:
        UpgradeVyos().rollback_backup_vyos()
    if gen_boot_config:
        UpgradeVyos().vyos_config_boot_gen()
    if gen_neutron_config:
        UpgradeVyos().vyos_neutron_config_gen()
    if back_neutron_db:
        UpgradeVyos().backup_db()        
    if migrate_neutron_db:
        UpgradeVyos().migrate_db()
    if upgrade_vsd:
        UpgradeVyos().upgrade_vsd()
    if rollback_db:
         UpgradeVyos().rollback_db()
    if ping_backup_vyos:
         UpgradeVyos().ping_backup_vyos()
    if ping_active_vyos:
         UpgradeVyos().ping_active_vyos()
    if exec_cmd_backup:
         UpgradeVyos().exec_cmd_on_backup(exec_cmd_backup)
    if exec_cmd_active:
         UpgradeVyos().exec_cmd_on_active(exec_cmd_active)
    if get_vsd_firewall:
        UpgradeVyos().get_vsd_firewall()
    if gen_nfv_group:
        UpgradeVyos().gen_nfv_group()
    if exec_cmd_host:
        UpgradeVyos().exec_cmd_host(exec_cmd_host)
    

if __name__ == '__main__':
    main()
